ARG BASE_IMG

FROM ${BASE_IMG}

RUN set -eux; \
    apk add --no-cache shadow su-exec tzdata; \
    groupadd -g 1000 docker; \
    useradd --no-log-init -s /bin/sh -u 1000 -g 1000 -d /config -o -c "" -m docker; \
    mkdir -p \
        /config \
        /data;

COPY user-entrypoint.sh /bin/user-entrypoint

ENTRYPOINT ["user-entrypoint"]

CMD ["sh"]

LABEL maintainer="Ryan Foster <phasecorex@gmail.com>"
