ARG BASE_IMG
FROM ${BASE_IMG}

RUN set -eux; \
    apk add --no-cache shadow su-exec tzdata; \
    groupadd --gid 1000 docker; \
    useradd --no-log-init --uid 1000 --gid 1000 --home-dir /config --shell /bin/false docker; \
    mkdir -p \
        /config \
        /data;

COPY user-entrypoint.sh /bin/user-entrypoint

ENTRYPOINT ["user-entrypoint"]

CMD ["sh"]
