ARG ARCH_IMG
FROM ${ARCH_IMG}

RUN set -eux; \
    apk add --no-cache bash shadow su-exec tzdata; \
    groupadd -g 1000 docker; \
    useradd --no-log-init -s /bin/bash -u 1000 -g 1000 -d /config -o -c "" -m docker; \
    mkdir -p \
        /app \
        /config \
        /data;

COPY user-entrypoint.sh /bin/user-entrypoint

ENTRYPOINT ["user-entrypoint"]

CMD ["bash"]

LABEL maintainer="Ryan Foster <phasecorex@gmail.com>"
