name: build_python

on:
  push:
    branches:
      - master
    paths:
      - user-entrypoint.sh
      - Dockerfile
      - .github/workflows/build_python.yml
  pull_request:
    branches:
      - master
    paths:
      - user-entrypoint.sh
      - Dockerfile
      - .github/workflows/build_python.yml
  repository_dispatch:
    types:
      - python_image_update
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      TITLE: User Python
    strategy:
      matrix:
        include:
          - base-image: python:3.13
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.13
              ghcr.io/phasecorex/user-python:3
              ghcr.io/phasecorex/user-python:latest
              docker.io/phasecorex/user-python:3.13
              docker.io/phasecorex/user-python:3
              docker.io/phasecorex/user-python:latest
            cache-from: ghcr.io/phasecorex/user-python:3.13
          - base-image: python:3.13-slim
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.13-slim
              ghcr.io/phasecorex/user-python:3-slim
              docker.io/phasecorex/user-python:3.13-slim
              docker.io/phasecorex/user-python:3-slim
            cache-from: ghcr.io/phasecorex/user-python:3.13-slim
          - base-image: python:3.13-alpine
            platforms: |-
              linux/amd64
              linux/arm/v6
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.13-alpine
              ghcr.io/phasecorex/user-python:3-alpine
              docker.io/phasecorex/user-python:3.13-alpine
              docker.io/phasecorex/user-python:3-alpine
            cache-from: ghcr.io/phasecorex/user-python:3.13-alpine
          - base-image: python:3.12
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.12
              docker.io/phasecorex/user-python:3.12
            cache-from: ghcr.io/phasecorex/user-python:3.12
          - base-image: python:3.12-slim
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.12-slim
              docker.io/phasecorex/user-python:3.12-slim
            cache-from: ghcr.io/phasecorex/user-python:3.12-slim
          - base-image: python:3.12-alpine
            platforms: |-
              linux/amd64
              linux/arm/v6
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.12-alpine
              docker.io/phasecorex/user-python:3.12-alpine
            cache-from: ghcr.io/phasecorex/user-python:3.12-alpine
          - base-image: python:3.11
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.11
              docker.io/phasecorex/user-python:3.11
            cache-from: ghcr.io/phasecorex/user-python:3.11
          - base-image: python:3.11-slim
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.11-slim
              docker.io/phasecorex/user-python:3.11-slim
            cache-from: ghcr.io/phasecorex/user-python:3.11-slim
          - base-image: python:3.11-alpine
            platforms: |-
              linux/amd64
              linux/arm/v6
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.11-alpine
              docker.io/phasecorex/user-python:3.11-alpine
            cache-from: ghcr.io/phasecorex/user-python:3.11-alpine
          - base-image: python:3.10
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.10
              docker.io/phasecorex/user-python:3.10
            cache-from: ghcr.io/phasecorex/user-python:3.10
          - base-image: python:3.10-slim
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.10-slim
              docker.io/phasecorex/user-python:3.10-slim
            cache-from: ghcr.io/phasecorex/user-python:3.10-slim
          - base-image: python:3.10-alpine
            platforms: |-
              linux/amd64
              linux/arm/v6
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.10-alpine
              docker.io/phasecorex/user-python:3.10-alpine
            cache-from: ghcr.io/phasecorex/user-python:3.10-alpine
          - base-image: python:3.9
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.9
              docker.io/phasecorex/user-python:3.9
            cache-from: ghcr.io/phasecorex/user-python:3.9
          - base-image: python:3.9-slim
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.9-slim
              docker.io/phasecorex/user-python:3.9-slim
            cache-from: ghcr.io/phasecorex/user-python:3.9-slim
          - base-image: python:3.9-alpine
            platforms: |-
              linux/amd64
              linux/arm/v6
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.9-alpine
              docker.io/phasecorex/user-python:3.9-alpine
            cache-from: ghcr.io/phasecorex/user-python:3.9-alpine
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: phasecorex/user-python
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.title=${{ env.TITLE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push ${{ matrix.base-image }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.tags }}
          cache-from: ${{ matrix.cache-from }}
          build-args: |
            BASE_IMG=${{ matrix.base-image }}
          labels: ${{ steps.meta.outputs.labels }}
