name: build_python

on:
  push:
    branches:
      - master
    paths:
      - user-entrypoint.sh
      - Dockerfile.alpine
      - Dockerfile.debian
      - .github/workflows/build_python.yml
      - su-exec/**
  pull_request:
    branches:
      - master
    paths:
      - user-entrypoint.sh
      - Dockerfile.alpine
      - Dockerfile.debian
      - .github/workflows/build_python.yml
      - su-exec/**
  repository_dispatch:
    types:
      - python_image_update

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      TITLE: User Python
    strategy:
      matrix:
        include:
          - base-image: python:3.9
            dockerfile: Dockerfile.debian
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.9
              ghcr.io/phasecorex/user-python:3
              ghcr.io/phasecorex/user-python:latest
              docker.io/phasecorex/user-python:3.9
              docker.io/phasecorex/user-python:3
              docker.io/phasecorex/user-python:latest
            cache-from: ghcr.io/phasecorex/user-python:3.9
          - base-image: python:3.9-slim
            dockerfile: Dockerfile.debian
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.9-slim
              ghcr.io/phasecorex/user-python:3-slim
              docker.io/phasecorex/user-python:3.9-slim
              docker.io/phasecorex/user-python:3-slim
            cache-from: ghcr.io/phasecorex/user-python:3.9-slim
          - base-image: python:3.9-alpine
            dockerfile: Dockerfile.alpine
            platforms: |-
              linux/amd64
              linux/arm/v6
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.9-alpine
              ghcr.io/phasecorex/user-python:3-alpine
              docker.io/phasecorex/user-python:3.9-alpine
              docker.io/phasecorex/user-python:3-alpine
            cache-from: ghcr.io/phasecorex/user-python:3.9-alpine
          - base-image: python:3.8
            dockerfile: Dockerfile.debian
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.8
              docker.io/phasecorex/user-python:3.8
            cache-from: ghcr.io/phasecorex/user-python:3.8
          - base-image: python:3.8-slim
            dockerfile: Dockerfile.debian
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.8-slim
              docker.io/phasecorex/user-python:3.8-slim
            cache-from: ghcr.io/phasecorex/user-python:3.8-slim
          - base-image: python:3.8-alpine
            dockerfile: Dockerfile.alpine
            platforms: |-
              linux/amd64
              linux/arm/v6
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.8-alpine
              docker.io/phasecorex/user-python:3.8-alpine
            cache-from: ghcr.io/phasecorex/user-python:3.8-alpine
          - base-image: python:3.7
            dockerfile: Dockerfile.debian
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.7
              docker.io/phasecorex/user-python:3.7
            cache-from: ghcr.io/phasecorex/user-python:3.7
          - base-image: python:3.7-slim
            dockerfile: Dockerfile.debian
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.7-slim
              docker.io/phasecorex/user-python:3.7-slim
            cache-from: ghcr.io/phasecorex/user-python:3.7-slim
          - base-image: python:3.7-alpine
            dockerfile: Dockerfile.alpine
            platforms: |-
              linux/amd64
              linux/arm/v6
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.7-alpine
              docker.io/phasecorex/user-python:3.7-alpine
            cache-from: ghcr.io/phasecorex/user-python:3.7-alpine
          - base-image: python:3.6
            dockerfile: Dockerfile.debian
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.6
              docker.io/phasecorex/user-python:3.6
            cache-from: ghcr.io/phasecorex/user-python:3.6
          - base-image: python:3.6-slim
            dockerfile: Dockerfile.debian
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.6-slim
              docker.io/phasecorex/user-python:3.6-slim
            cache-from: ghcr.io/phasecorex/user-python:3.6-slim
          - base-image: python:3.6-alpine
            dockerfile: Dockerfile.alpine
            platforms: |-
              linux/amd64
              linux/arm/v6
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
            tags: |-
              ghcr.io/phasecorex/user-python:3.6-alpine
              docker.io/phasecorex/user-python:3.6-alpine
            cache-from: ghcr.io/phasecorex/user-python:3.6-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Repo metadata
        id: repo
        uses: actions/github-script@v5
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push ${{ matrix.base-image }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.tags }}
          cache-from: ${{ matrix.cache-from }}
          build-args: |
            BASE_IMG=${{ matrix.base-image }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.title=${{ env.TITLE }}
            org.opencontainers.image.description=${{ fromJson(steps.repo.outputs.result).description }}
            org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
